-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Tapahtumakategoria CASCADE;

DROP TABLE IF EXISTS Kategoria CASCADE;

DROP TABLE IF EXISTS Tilitapahtuma CASCADE;

DROP TABLE IF EXISTS Admin CASCADE;

DROP TABLE IF EXISTS Opiskelija CASCADE;
